# coding=utf-8
# the version  is value
# of contextvariable dictversion.
# It is suffixed with this 'microversion', which should be #  changed often.
microversion = '.002'  # abch 11-19-2023
alldictparms = {
 "gra": {
  "dictup":"GRA",
  "dictlo":"gra",
  "dictname":u"Grassman Wörterbuch zum Rig Veda",
  "dictversion":"02",
 },
 "bur": {
  "dictup":"BUR",
  "dictlo":"bur",
  "dictname":u"Burnouf Dictionnaire Sanscrit-Français",
  "dictversion":"02",
 },
"cae": {
  "dictup":"CAE",
  "dictlo":"cae",
  "dictname":u"Cappeller Sanskrit-English Dictionary",
  "dictversion":"02",
 },
 "stc": {
  "dictup":"STC",
  "dictlo":"stc",
  "dictname":u"Stchoupak Dictionnaire Sanscrit-Français",
  "dictversion":"02",
 },
"pwg": {
  "dictup":"PWG",
  "dictlo":"pwg",
  "dictname":u"Böhtlingk and Roth Grosses Petersburger Wörterbuch",
  "dictversion":"02",
 },
 "mw": {
  "dictup":"MW",
  "dictlo":"mw",
  "dictname":u"Monier-Williams Sanskrit-English Dictionary, 1899",
  "dictversion":"02",
 },
 "skd": {
  "dictup":"SKD",
  "dictlo":"skd",
  "dictname":u"Sabda-kalpadruma",
  "dictversion":"02",
 },
 "ae": {
  "dictup":"AE",
  "dictlo":"ae",
  "dictname":u"Apte Student's English-Sanskrit Dictionary",
  "dictversion":"02",
 },
"pw": {
  "dictup":"PW",
  "dictlo":"pw",
  "dictname":u"Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung",
  "dictversion":"02",
 },
"ap90": {
  "dictup":"AP90",
  "dictlo":"ap90",
  "dictname":u"Apte Practical Sanskrit-English Dictionary, 1890",
  "dictversion":"02",
 },
"ap": {
  "dictup":"AP",
  "dictlo":"ap",
  "dictname":u"Apte Practical Sanskrit-English Dictionary, revised edition, 1957",
  "dictversion":"02",
 },
"pd": {
  "dictup":"PD",
  "dictlo":"pd",
  "dictname":u"An Encyclopedic Dictionary of Sanskrit on Historical Principles",
  "dictversion":"02",
 },
"bhs": {
  "dictup":"BHS",
  "dictlo":"bhs",
  "dictname":u"Edgerton Buddhist Hybrid Sanskrit Dictionary",
  "dictversion":"02",
 },
"wil": {
  "dictup":"WIL",
  "dictlo":"wil",
  "dictname":u"Wilson Sanskrit-English Dictionary",
  "dictversion":"02",
 },
"yat": {
  "dictup":"YAT",
  "dictlo":"yat",
  "dictname":u"Yates Sanskrit-English Dictionary",
  "dictversion":"02",
 },
"shs": {
  "dictup":"SHS",
  "dictlo":"shs",
  "dictname":u"Shabda-Sagara Sanskrit-English Dictionary",
  "dictversion":"02",
 },
"gst": {
  "dictup":"GST",
  "dictlo":"gst",
  "dictname":u"Goldstücker Sanskrit-English Dictionary",
  "dictversion":"02",
 },
"vcp": {
  "dictup":"VCP",
  "dictlo":"vcp",
  "dictname":u"Vacaspatyam",
  "dictversion":"02",
 },
"ben": {
  "dictup":"BEN",
  "dictlo":"ben",
  "dictname":u"Benfey Sanskrit-English Dictionary",
  "dictversion":"02",
 },
"bop": {
  "dictup":"BOP",
  "dictlo":"bop",
  "dictname":u"Bopp Glossarium Sanscritum",
  "dictversion":"02",
 },
"bor": {
  "dictup":"BOR",
  "dictlo":"bor",
  "dictname":u"Borooah English-Sanskrit Dictionary",
  "dictversion":"02",
 },
"ccs": {
  "dictup":"CCS",
  "dictlo":"ccs",
  "dictname":u"Cappeller Sanskrit Wörterbuch",
  "dictversion":"02",
 },
"md": {
  "dictup":"MD",
  "dictlo":"md",
  "dictname":u"Macdonell Sanskrit-English Dictionary",
  "dictversion":"02",
 },
"mwe": {
  "dictup":"MWE",
  "dictlo":"mwe",
  "dictname":u"Monier-Williams English-Sanskrit Dictionary",
  "dictversion":"02",
 },
"mw72": {
  "dictup":"MW72",
  "dictlo":"mw72",
  "dictname":u"Monier-Williams Sanskrit-English Dictionary, 1872",
  "dictversion":"02",
 },
"ieg": {
  "dictup":"IEG",
  "dictlo":"ieg",
  "dictname":u"Indian Epigraphical Glossary",
  "dictversion":"02",
 },
"inm": {
  "dictup":"INM",
  "dictlo":"inm",
  "dictname":u"Index to the Names in the Mahabharata",
  "dictversion":"02",
 },
"krm": {
  "dictup":"KRM",
  "dictlo":"krm",
  "dictname":u"Kṛdantarūpamālā",
  "dictversion":"02",
 },
"mci": {
  "dictup":"MCI",
  "dictlo":"mci",
  "dictname":u"Mehendale Mahabharata Cultural Index",
  "dictversion":"02",
 },
"pe": {
  "dictup":"PE",
  "dictlo":"pe",
  "dictname":u"Puranic Encyclopedia",
  "dictversion":"02",
 },
"pgn": {
  "dictup":"PGN",
  "dictlo":"pgn",
  "dictname":u"Personal and Geographical Names in the Gupta Inscriptions",
  "dictversion":"02",
 },
"pui": {
  "dictup":"PUI",
  "dictlo":"pui",
  "dictname":u"The Purana Index",
  "dictversion":"02",
 },
"sch": {
  "dictup":"SCH",
  "dictlo":"sch",
  "dictname":u"Schmidt Nachträge zum Sanskrit-Wörterbuch",
  "dictversion":"02",
 },
"snp": {
  "dictup":"SNP",
  "dictlo":"snp",
  "dictname":u"Meulenbeld Sanskrit Names of Plants",
  "dictversion":"02",
 },
"vei": {
  "dictup":"VEI",
  "dictlo":"vei",
  "dictname":u"The Vedic Index of Names and Subjects",
  "dictversion":"02",
 },
"acc": {
  "dictup":"ACC",
  "dictlo":"acc",
  "dictname":u"Aufrecht Catalogus Catalogorum",
  "dictversion":"02",
 },
"lan": {
  "dictup":"LAN",
  "dictlo":"lan",
  "dictname":u"Lanman Sanskrit Reader Vocabulary",
  "dictversion":"02",
 },
"armh": {
  "dictup":"ARMH",
  "dictlo":"armh",
  "dictname":u"Abhidhānaratnamālā of Halāyudha",
  "dictversion":"02",
 },
"pwkvn": {
  "dictup":"PWKVN",
  "dictlo":"pwkvn",
  "dictname":u"Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung, Nachträge und Verbesserungen",
  "dictversion":"02",
 },
"lrv": {
  "dictup":"LRV",
  "dictlo":"lrv",
  "dictname":u"Vaidya Standard Sanskrit-English Dictionary",
  "dictversion":"02",
 },

 "abch": {
  "dictup":"ABCH",
  "dictlo":"abch",
  "dictname":u"Abhidhānacintāmaṇi of Hemacandrācārya",
  "dictversion":"03",
 },

}
