sh generate_dict.sh acc  ../../acc
sh generate_dict.sh ae  ../../ae
sh generate_dict.sh ap90  ../../ap90
sh generate_dict.sh ap  ../../ap
sh generate_dict.sh ben  ../../ben
sh generate_dict.sh bhs  ../../bhs
sh generate_dict.sh bop  ../../bop
sh generate_dict.sh bor  ../../bor
sh generate_dict.sh bur  ../../bur
sh generate_dict.sh cae  ../../cae
sh generate_dict.sh ccs  ../../ccs
sh generate_dict.sh gra  ../../gra
sh generate_dict.sh gst  ../../gst
sh generate_dict.sh ieg  ../../ieg
sh generate_dict.sh inm  ../../inm
sh generate_dict.sh krm  ../../krm
sh generate_dict.sh mci  ../../mci
sh generate_dict.sh md  ../../md
sh generate_dict.sh mw  ../../mw
sh generate_dict.sh mw72  ../../mw72
sh generate_dict.sh mwe  ../../mwe
sh generate_dict.sh pd  ../../pd
sh generate_dict.sh pe  ../../pe
sh generate_dict.sh pgn  ../../pgn
sh generate_dict.sh pui  ../../pui
sh generate_dict.sh pw  ../../pw
sh generate_dict.sh pwg  ../../pwg
sh generate_dict.sh sch  ../../sch
sh generate_dict.sh shs  ../../shs
sh generate_dict.sh skd  ../../skd
sh generate_dict.sh snp  ../../snp
sh generate_dict.sh stc  ../../stc
sh generate_dict.sh vcp  ../../vcp
sh generate_dict.sh vei  ../../vei
sh generate_dict.sh wil  ../../wil
sh generate_dict.sh yat  ../../yat
sh generate_dict.sh lan  ../../lan
sh generate_dict.sh armh  ../../armh
sh generate_dict.sh pwkvn  ../../pwkvn
sh generate_dict.sh lrv  ../../lrv


