sh generate_dict.sh acc  ../../ACCScan/2020/
sh generate_dict.sh ae  ../../AEScan/2020/
sh generate_dict.sh ap  ../../APScan/2020/
sh generate_dict.sh ap90  ../../AP90Scan/2020/
sh generate_dict.sh ben  ../../BENScan/2020/
sh generate_dict.sh bhs  ../../BHSScan/2020/
sh generate_dict.sh bop  ../../BOPScan/2020/
sh generate_dict.sh bor  ../../BORScan/2020/
sh generate_dict.sh bur  ../../BURScan/2020/
sh generate_dict.sh cae  ../../CAEScan/2020/
sh generate_dict.sh ccs  ../../CCSScan/2020/
sh generate_dict.sh gra  ../../GRAScan/2020/
sh generate_dict.sh gst  ../../GSTScan/2020/
sh generate_dict.sh ieg  ../../IEGScan/2020/
sh generate_dict.sh inm  ../../INMScan/2020/
sh generate_dict.sh krm  ../../KRMScan/2020/
sh generate_dict.sh mci  ../../MCIScan/2020/
sh generate_dict.sh md  ../../MDScan/2020/
sh generate_dict.sh mw  ../../MWScan/2020/
sh generate_dict.sh mw72  ../../MW72Scan/2020/
sh generate_dict.sh mwe  ../../MWEScan/2020/
sh generate_dict.sh pd  ../../PDScan/2020/
sh generate_dict.sh pe  ../../PEScan/2020/
sh generate_dict.sh pgn  ../../PGNScan/2020/
sh generate_dict.sh pui  ../../PUIScan/2020/
sh generate_dict.sh pw  ../../PWScan/2020/
sh generate_dict.sh pwg  ../../PWGScan/2020/
sh generate_dict.sh sch  ../../SCHScan/2020/
sh generate_dict.sh shs  ../../SHSScan/2020/
sh generate_dict.sh skd  ../../SKDScan/2020/
sh generate_dict.sh snp  ../../SNPScan/2020/
sh generate_dict.sh stc  ../../STCScan/2020/
sh generate_dict.sh vcp  ../../VCPScan/2020/
sh generate_dict.sh vei  ../../VEIScan/2020/
sh generate_dict.sh wil  ../../WILScan/2020/
sh generate_dict.sh yat  ../../YATScan/2020/
sh generate_dict.sh lan  ../../LANScan/2020/
sh generate_dict.sh armh  ../../ARMHScan/2020/
sh generate_dict.sh pwkvn  ../../PWKVNScan/2020/
sh generate_dict.sh lrv  ../../LRVScan/2022/
sh generate_dict.sh abch  ../../ABCHScan/2023/

