# coding=utf-8
# the version (in webtc/dictcode.php) is value
# of contextvariable dictwebversion.
# It is suffixed with this 'microversion', which should be
#  changed often.
microversion = '.003'
alldictparms = {
 "gra": {
  "dictup":"GRA",
  "dictlo":"gra",
  "dictname":u"Grassman Wörterbuch zum Rig Veda",
  "dictwebversion":"00",
  "dictyear":"2014",  # for Cologne file system location
  "dictaccent":False,
  "webtc2devatextoption":False,
  # next is similar to webtc/dictinfo.php $english.
  # current use (07-09-2018) in webtc1/listhierview for styling headwords
  # in the list. This is handled by a dictionary code check in listhier.
 },
 "bur": {
  "dictup":"BUR",
  "dictlo":"bur",
  "dictname":u"Burnouf Dictionnaire Sanscrit-Français",
  "dictwebversion":"00",
  "dictyear":"2013",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"cae": {
  "dictup":"CAE",
  "dictlo":"cae",
  "dictname":u"Cappeller Sanskrit-English Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":True,
  "webtc2devatextoption":True,
 },
 "stc": {
  "dictup":"STC",
  "dictlo":"stc",
  "dictname":u"Stchoupak Dictionnaire Sanscrit-Français",
  "dictwebversion":"00",
  "dictyear":"2013",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"pwg": {
  "dictup":"PWG",
  "dictlo":"pwg",
  "dictname":u"Böhtlingk and Roth Grosses Petersburger Wörterbuch",
  "dictwebversion":"00",
  "dictyear":"2013",
  "dictaccent":True,
  "webtc2devatextoption":True,
 },
 "mw": {
  "dictup":"MW",
  "dictlo":"mw",
  "dictname":u"Monier-Williams Sanskrit-English Dictionary, 1899",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":True,
  "webtc2devatextoption":True,
 },
 "skd": {
  "dictup":"SKD",
  "dictlo":"skd",
  "dictname":u"Sabda-kalpadruma",
  "dictwebversion":"00",
  "dictyear":"2013",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
 "ae": {
  "dictup":"AE",
  "dictlo":"ae",
  "dictname":u"Apte Student's English-Sanskrit Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"pw": {
  "dictup":"PW",
  "dictlo":"pw",
  "dictname":u"Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":True,
  "webtc2devatextoption":True,
 },
"ap90": {
  "dictup":"AP90",
  "dictlo":"ap90",
  "dictname":u"Apte Practical Sanskrit-English Dictionary, 1890",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"ap": {
  "dictup":"AP",
  "dictlo":"ap",
  "dictname":u"Apte Practical Sanskrit-English Dictionary, revised edition, 1957",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"pd": {
  "dictup":"PD",
  "dictlo":"pd",
  "dictname":u"An Encyclopedic Dictionary of Sanskrit on Historical Principles",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":True,
  "webtc2devatextoption":True,
 },
"bhs": {
  "dictup":"BHS",
  "dictlo":"bhs",
  "dictname":u"Edgerton Buddhist Hybrid Sanskrit Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"wil": {
  "dictup":"WIL",
  "dictlo":"wil",
  "dictname":u"Wilson Sanskrit-English Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"yat": {
  "dictup":"YAT",
  "dictlo":"yat",
  "dictname":u"Yates Sanskrit-English Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"shs": {
  "dictup":"SHS",
  "dictlo":"shs",
  "dictname":u"Shabda-Sagara Sanskrit-English Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"gst": {
  "dictup":"GST",
  "dictlo":"gst",
  "dictname":u"Goldstücker Sanskrit-English Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"vcp": {
  "dictup":"VCP",
  "dictlo":"vcp",
  "dictname":u"Vacaspatyam",
  "dictwebversion":"00",
  "dictyear":"2020",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"ben": {
  "dictup":"BEN",
  "dictlo":"ben",
  "dictname":u"Benfey Sanskrit-English Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"bop": {
  "dictup":"BOP",
  "dictlo":"bop",
  "dictname":u"Bopp Glossarium Sanscritum",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"bor": {
  "dictup":"BOR",
  "dictlo":"bor",
  "dictname":u"Borooah English-Sanskrit Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"ccs": {
  "dictup":"CCS",
  "dictlo":"ccs",
  "dictname":u"Cappeller Sanskrit Wörterbuch",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":True,
  "webtc2devatextoption":True,
 },
"md": {
  "dictup":"MD",
  "dictlo":"md",
  "dictname":u"Macdonell Sanskrit-English Dictionary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"mwe": {
  "dictup":"MWE",
  "dictlo":"mwe",
  "dictname":u"Monier-Williams English-Sanskrit Dictionary",
  "dictwebversion":"00",
  "dictyear":"2013",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"mw72": {
  "dictup":"MW72",
  "dictlo":"mw72",
  "dictname":u"Monier-Williams Sanskrit-English Dictionary, 1872",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"ieg": {
  "dictup":"IEG",
  "dictlo":"ieg",
  "dictname":u"Indian Epigraphical Glossary",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"inm": {
  "dictup":"INM",
  "dictlo":"inm",
  "dictname":u"Index to the Names in the Mahabharata",
  "dictwebversion":"00",
  "dictyear":"2013",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"krm": {
  "dictup":"KRM",
  "dictlo":"krm",
  "dictname":u"Kṛdantarūpamālā",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":True,
 },
"mci": {
  "dictup":"MCI",
  "dictlo":"mci",
  "dictname":u"Mehendale Mahabharata Cultural Index",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"pe": {
  "dictup":"PE",
  "dictlo":"pe",
  "dictname":u"Puranic Encyclopedia",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"pgn": {
  "dictup":"PGN",
  "dictlo":"pgn",
  "dictname":u"Personal and Geographical Names in the Gupta Inscriptions",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"pui": {
  "dictup":"PUI",
  "dictlo":"pui",
  "dictname":u"The Purana Index",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"sch": {
  "dictup":"SCH",
  "dictlo":"sch",
  "dictname":u"Schmidt Nachträge zum Sanskrit-Wörterbuch",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"snp": {
  "dictup":"SNP",
  "dictlo":"snp",
  "dictname":u"Meulenbeld Sanskrit Names of Plants",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"vei": {
  "dictup":"VEI",
  "dictlo":"vei",
  "dictname":u"The Vedic Index of Names and Subjects",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },
"acc": {
  "dictup":"ACC",
  "dictlo":"acc",
  "dictname":u"Aufrecht Catalogus Catalogorum",
  "dictwebversion":"00",
  "dictyear":"2014",
  "dictaccent":False,
  "webtc2devatextoption":False,
 },

}

"""
   array("ACC"=>"2014" , "AE"=>"2014" , "AP"=>"2014" , "AP90"=>"2014",
       "BEN"=>"2014" , "BHS"=>"2014" , "BOP"=>"2014" , "BOR"=>"2014",
       "BUR"=>"2013" , "CAE"=>"2014" , "CCS"=>"2014" , "GRA"=>"2014",
       "GST"=>"2014" , "IEG"=>"2014" , "INM"=>"2013" , "KRM"=>"2014",
       "MCI"=>"2014" , "MD"=>"2014" , "MW"=>"2014" , "MW72"=>"2014",
       "MWE"=>"2013" , "PD"=>"2014" , "PE"=>"2014" , "PGN"=>"2014",
       "PUI"=>"2014" , "PWG"=>"2013" , "PW"=>"2014" , "SCH"=>"2014",
       "SHS"=>"2014" , "SKD"=>"2013" , "SNP"=>"2014" , "STC"=>"2013",
       "VCP"=>"2013" , "VEI"=>"2014" , "WIL"=>"2014" , "YAT"=>"2014");
"""
